[package]
name = "sso-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
bytes = "1.3.0"
futures-util = "0.3.25"
regex = "1.7.0"

dashmap = "5.4.0"
lazy_static = "1.4.0"
once_cell = "1.17.0"

aes-gcm = "0.10.1"
bcrypt = "0.13.0"
rand = "0.8.5"

reqwest = "0.11.13"
warp = "0.3.3"
warp-real-ip = "0.2.0"
serde = "1.0.152"
serde_json = "1.0.91"

mongodb = "2.3.1"
jsonwebtoken = "8.2.0"

lettre = "0.10"

base64 = "0.20.0"
totp-rs = { version = "4.1.0", features = ["qr"] }
