[package]
name = "sso-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.11.0", features = ["attributes", "tokio1"] }
futures-util = "0.3"

dashmap = "5.3.4"
lazy_static = "1.4.0"
once_cell = "1.4.0"

aes-gcm = "0.9.4"
bcrypt = "0.13.0"
rand = "0.8.5"

warp = "0.3.2"
serde = "1.0.137"
mongodb = "2.2.1"
jsonwebtoken = "8.1.0"

base64 = "0.13.0"
totp-rs = { version = "2.0.1", features = ["qr"] }
