[package]
name = "sso-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
bytes = "1.2.1"
futures-util = "0.3.23"

dashmap = "5.3.4"
lazy_static = "1.4.0"
once_cell = "1.13.1"

aes-gcm = "0.10.1"
bcrypt = "0.13.0"
rand = "0.8.5"

reqwest = "0.11.11"
warp = "0.3.2"
warp-real-ip = "0.2.0"
serde = "1.0.144"
serde_json = "1.0.83"

mongodb = "2.3.0"
jsonwebtoken = "8.1.1"

lettre = "0.10"

base64 = "0.13.0"
totp-rs = { version = "3.0.1", features = ["qr"] }
