version: "3.9"

networks:
  default:
    name: nextflow

services:
  sso-system:
    build: .
    environment:
      - MONGODB_URI=mongodb://sso-system-mongodb:27017
      - MONGODB_DATABASE=sso
      - CDN_MONGODB_DATABASE=cdn
      - JWT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - HCAPTCHA_SECRET=0x0000000000000000000000000000000000000000
      - CORS_ORIGINS=https://www.example.com
      - HOST=0.0.0.0:9000
    restart: always
  sso-system-mongodb:
    image: mongo
    volumes: ./database:/data/db
    restart: always
